/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package selectStation;

import centralStation.Juega;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Andrea
 */
public class SelecNave extends javax.swing.JFrame {

    /**
     * Creates new form SelecNave
     */
    public SelecNave() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        atras = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        naveUno = new javax.swing.JButton();
        naveDos = new javax.swing.JButton();
        naveTres = new javax.swing.JButton();
        naveCuatro = new javax.swing.JButton();
        naveCinco = new javax.swing.JButton();
        naveSeis = new javax.swing.JButton();
        naveSiete = new javax.swing.JButton();
        naveSIete1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atras.setBackground(new java.awt.Color(0, 0, 0));
        atras.setForeground(new java.awt.Color(255, 255, 255));
        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Juega/loginA.png"))); // NOI18N
        atras.setBorder(null);
        atras.setBorderPainted(false);
        atras.setContentAreaFilled(false);
        atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atras.setFocusPainted(false);
        atras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Juega/login (2).png"))); // NOI18N
        atras.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Juega/login (2).png"))); // NOI18N
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, -1, -1));

        jLabel31.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("SELECCIÓN DE NAVE");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 430, 60));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 50, 50));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 50, 50));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 50, 50));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 50, 50));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 50, 50));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 50, 50));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 50, 50));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 50, 50));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 50, 50));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 50, 50));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 50, 50));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 50, 50));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 50));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 50, 50));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 50, 50));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 50, 50));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 50, 50));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 50, 50));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 50, 50));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 50, 50));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 50, 50));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 50, 50));

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 50, 50));

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 50, 50));

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 50, 50));

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Lobby/star.png"))); // NOI18N
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 50, 50));

        naveUno.setBackground(new java.awt.Color(0, 0, 0));
        naveUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Seleccion/nave1.png"))); // NOI18N
        naveUno.setBorder(null);
        naveUno.setBorderPainted(false);
        naveUno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        naveUno.setFocusPainted(false);
        naveUno.setPreferredSize(new java.awt.Dimension(150, 150));
        naveUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naveUnoActionPerformed(evt);
            }
        });
        jPanel1.add(naveUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        naveDos.setBackground(new java.awt.Color(0, 0, 0));
        naveDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Seleccion/nave2.png"))); // NOI18N
        naveDos.setActionCommand("");
        naveDos.setBorder(null);
        naveDos.setBorderPainted(false);
        naveDos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        naveDos.setFocusPainted(false);
        naveDos.setPreferredSize(new java.awt.Dimension(150, 150));
        naveDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naveDosActionPerformed(evt);
            }
        });
        jPanel1.add(naveDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        naveTres.setBackground(new java.awt.Color(0, 0, 0));
        naveTres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Seleccion/nave3.png"))); // NOI18N
        naveTres.setBorder(null);
        naveTres.setBorderPainted(false);
        naveTres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        naveTres.setFocusPainted(false);
        naveTres.setPreferredSize(new java.awt.Dimension(150, 150));
        naveTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naveTresActionPerformed(evt);
            }
        });
        jPanel1.add(naveTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        naveCuatro.setBackground(new java.awt.Color(0, 0, 0));
        naveCuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Seleccion/nave4.png"))); // NOI18N
        naveCuatro.setBorder(null);
        naveCuatro.setBorderPainted(false);
        naveCuatro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        naveCuatro.setFocusPainted(false);
        naveCuatro.setPreferredSize(new java.awt.Dimension(150, 150));
        naveCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naveCuatroActionPerformed(evt);
            }
        });
        jPanel1.add(naveCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, -1, -1));

        naveCinco.setBackground(new java.awt.Color(0, 0, 0));
        naveCinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Seleccion/nave5.png"))); // NOI18N
        naveCinco.setBorder(null);
        naveCinco.setBorderPainted(false);
        naveCinco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        naveCinco.setFocusPainted(false);
        naveCinco.setPreferredSize(new java.awt.Dimension(150, 150));
        naveCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naveCincoActionPerformed(evt);
            }
        });
        jPanel1.add(naveCinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        naveSeis.setBackground(new java.awt.Color(0, 0, 0));
        naveSeis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Seleccion/nave6.png"))); // NOI18N
        naveSeis.setBorder(null);
        naveSeis.setBorderPainted(false);
        naveSeis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        naveSeis.setFocusPainted(false);
        naveSeis.setPreferredSize(new java.awt.Dimension(150, 150));
        naveSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naveSeisActionPerformed(evt);
            }
        });
        jPanel1.add(naveSeis, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        naveSiete.setBackground(new java.awt.Color(0, 0, 0));
        naveSiete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Seleccion/nave7.png"))); // NOI18N
        naveSiete.setBorder(null);
        naveSiete.setBorderPainted(false);
        naveSiete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        naveSiete.setFocusPainted(false);
        naveSiete.setPreferredSize(new java.awt.Dimension(150, 150));
        naveSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naveSieteActionPerformed(evt);
            }
        });
        jPanel1.add(naveSiete, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, -1));

        naveSIete1.setBackground(new java.awt.Color(0, 0, 0));
        naveSIete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Seleccion/nave8.png"))); // NOI18N
        naveSIete1.setBorder(null);
        naveSIete1.setBorderPainted(false);
        naveSIete1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        naveSIete1.setFocusPainted(false);
        naveSIete1.setPreferredSize(new java.awt.Dimension(150, 150));
        naveSIete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naveSIete1ActionPerformed(evt);
            }
        });
        jPanel1.add(naveSIete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        SelecPistas mnpista=new SelecPistas();
        this.toBack();
        this.setVisible(false);
        try {
            this.finalize();
        } catch (Throwable ex) {
            Logger.getLogger(SelecPistas.class.getName()).log(Level.SEVERE, null, ex);
        }
        mnpista.setVisible(true);
    }//GEN-LAST:event_atrasActionPerformed

    private void naveDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naveDosActionPerformed
        Mauricio naveDos=new Mauricio();
        this.toBack();
        this.setVisible(false);
        try {
            this.finalize();
        } catch (Throwable ex) {
            Logger.getLogger(SelecNave.class.getName()).log(Level.SEVERE, null, ex);
        }
        naveDos.setVisible(true);
    }//GEN-LAST:event_naveDosActionPerformed

    private void naveCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naveCuatroActionPerformed
        Brenda naveCuatro=new Brenda();
        this.toBack();
        this.setVisible(false);
        try {
            this.finalize();
        } catch (Throwable ex) {
            Logger.getLogger(SelecNave.class.getName()).log(Level.SEVERE, null, ex);
        }
        naveCuatro.setVisible(true);
    }//GEN-LAST:event_naveCuatroActionPerformed

    private void naveTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naveTresActionPerformed
        Adrian naveTres=new Adrian();
        this.toBack();
        this.setVisible(false);
        try {
            this.finalize();
        } catch (Throwable ex) {
            Logger.getLogger(SelecNave.class.getName()).log(Level.SEVERE, null, ex);
        }
        naveTres.setVisible(true);
    }//GEN-LAST:event_naveTresActionPerformed

    private void naveCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naveCincoActionPerformed
        Carlos naveCinco=new Carlos();
        this.toBack();
        this.setVisible(false);
        try {
            this.finalize();
        } catch (Throwable ex) {
            Logger.getLogger(SelecNave.class.getName()).log(Level.SEVERE, null, ex);
        }
        naveCinco.setVisible(true);
    }//GEN-LAST:event_naveCincoActionPerformed

    private void naveSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naveSeisActionPerformed
        Daniel naveSeis=new Daniel();
        this.toBack();
        this.setVisible(false);
        try {
            this.finalize();
        } catch (Throwable ex) {
            Logger.getLogger(SelecNave.class.getName()).log(Level.SEVERE, null, ex);
        }
        naveSeis.setVisible(true);
    }//GEN-LAST:event_naveSeisActionPerformed

    private void naveSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naveSieteActionPerformed
        Ernesto naveSiete=new Ernesto();
        this.toBack();
        this.setVisible(false);
        try {
            this.finalize();
        } catch (Throwable ex) {
            Logger.getLogger(SelecNave.class.getName()).log(Level.SEVERE, null, ex);
        }
        naveSiete.setVisible(true);
    }//GEN-LAST:event_naveSieteActionPerformed

    private void naveSIete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naveSIete1ActionPerformed
        Gustavo naveOcho=new Gustavo();
        this.toBack();
        this.setVisible(false);
        try {
            this.finalize();
        } catch (Throwable ex) {
            Logger.getLogger(SelecNave.class.getName()).log(Level.SEVERE, null, ex);
        }
        naveOcho.setVisible(true);
    }//GEN-LAST:event_naveSIete1ActionPerformed

    private void naveUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naveUnoActionPerformed
        Andrea naveUno=new Andrea();
        this.toBack();
        this.setVisible(false);
        try {
            this.finalize();
        } catch (Throwable ex) {
            Logger.getLogger(SelecNave.class.getName()).log(Level.SEVERE, null, ex);
        }
        naveUno.setVisible(true);
    }//GEN-LAST:event_naveUnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelecNave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton naveCinco;
    private javax.swing.JButton naveCuatro;
    private javax.swing.JButton naveDos;
    private javax.swing.JButton naveSIete1;
    private javax.swing.JButton naveSeis;
    private javax.swing.JButton naveSiete;
    private javax.swing.JButton naveTres;
    private javax.swing.JButton naveUno;
    // End of variables declaration//GEN-END:variables
}
